name: Trigger Netlify Build
on:
  schedule:
    # Run at 6AM and 4PM daily
    - cron: "00 11,21 * * *"
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5d93f0dfe3c073e2486f5f04
