name: Trigger Netlify Build
on:
  schedule:
    # Run at 0000, 0600, 1200, 1800 daily
    - cron: '00 0,6,12,18 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5d93f0dfe3c073e2486f5f04